# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 22:22
from __future__ import unicode_literals

import adapter.models
from decimal import Decimal
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rehive_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('secret', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, max_length=6, null=True)),
                ('unit', models.CharField(blank=True, max_length=15, null=True)),
                ('divisibility', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('rehive_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('recipient', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', adapter.models.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=28)),
                ('issuer', models.CharField(blank=True, max_length=200, null=True)),
                ('rehive_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('status', models.CharField(blank=True, choices=[('Waiting', 'Waiting'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Complete', 'Complete'), ('Failed', 'Failed')], db_index=True, max_length=24, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adapter.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_type', models.CharField(blank=True, max_length=50, null=True)),
                ('webhook_id', models.CharField(blank=True, max_length=50, null=True)),
                ('callback_url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SendTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('rehive_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('recipient', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', adapter.models.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=28)),
                ('issuer', models.CharField(blank=True, max_length=200, null=True)),
                ('rehive_request', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('admin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adapter.AdminAccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adapter.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rehive_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('admin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adapter.AdminAccount')),
            ],
        ),
        migrations.AddField(
            model_name='receivewebhook',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adapter.UserAccount'),
        ),
        migrations.AddField(
            model_name='receivetransaction',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adapter.UserAccount'),
        ),
    ]
